name: Run Python Script Hourly

on:
  schedule:
    - cron: '0 * * * *'  # כל שעה עגולה
  workflow_dispatch:     # מאפשר להריץ ידנית גם כן

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt || true
      - name: Run script
        run: python sync.py

