name: Run Sync Hourly

on:
  schedule:
    - cron: '0 * * * *'  # כל שעה עגולה
  workflow_dispatch:     # מאפשר גם להריץ ידנית

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run jira_fetch.py (to generate hp_mapping.json)
        run: python jira_fetch.py

      - name: Run sync script
        run: python sync.py
