name: Run Jira-Gmail Sync

on:
  schedule:
    - cron: '0 * * * *'  # כל שעה עגולה
  workflow_dispatch:     # הרצה ידנית מה-UI של גיטהאב

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
      EMAIL: ${{ secrets.EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run jira_fetch.py (to generate mapping file)
        run: python jira_fetch.py

      - name: Run jira_gmail_sync.py (to match emails and update Jira)
        run: python jira_gmail_sync.py
